In [1]:
import numpy as np

numpy는 내부적으로 c로 구현이 되어있다
* 수치에 관련된 프로그래밍을 할 때 일반 python보다 빠름
* 특히 연산에 특화되어 있음

In [2]:
# 일반 파이썬 리스트를 numpy 배열화 ( numpy 배열 : ndarray )
py_list = [1, 2, 3]
arr1 = np.array(py_list)
arr1

array([1, 2, 3])

In [5]:
# type 확인
type(arr1)

numpy.ndarray

In [4]:
py_list = [[1, 2, 3],
          [4, 5, 6]]
arr2 = np.array(py_list)
type(arr2)

numpy.ndarray

* numpy 에서는 숫자 배열을 만들기 위한 여러가지 함수를 제공

## np.arange

In [6]:
# np.arange 함수는 파이썬의 range 함수와 유사
arr = np.arange(10) # 0 ~ 9 까지 배열 생성
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr = np.arange(1, 10) # 1 ~ 9 까지 배욜 생성
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr = np.arange(1, 10, 2) # 1부터 9까지 2씩 건너뛰며 배열 생성
arr

array([1, 3, 5, 7, 9])

## 다차원 배열
* np.zeros
* np.ones
* np.full

### np.zeros
* 지정 차원에 모든 원소를 **0**으로 채운다

In [9]:
np.zeros(5) # 1차원 배열에 5개의 0을 채운다

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((4, 5)) # 4행 5열(2차원)의 배열에 0을 채운다

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((3, 4, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

### np.ones

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.ones((4, 5)) * 3

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

### np.full
* 지정한 차원에 모든 원소를 원하는 수로 채운다

In [18]:
np.full((3, 4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

## 단위 행렬
* np.eye
* 단위 행렬 : 대각선 방향의 원소가 1이고, 나머지 원소는 0인 행렬

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## 구간 나누기
* np.linspace

In [21]:
np.linspace(1, 10, 3) # 1부터 10까지 2개의 구간 만들기

array([ 1. ,  5.5, 10. ])

In [22]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [23]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

## Random을 사용하기 위한 numpy
* 보통 랜덤한 배열은 딥러닝에서 매개변수의 초기화를 하기 위해 사용
* 딥러닝에서 일반적으로 Xavier 초깃값, He 초깃값, 정규분포 초깃값을 계산

### np.random.rand
* 완전한 random 만들기( 정규분포나 균등분포가 아닌 랜덤값 )

In [24]:
np.random.rand(2, 3) # 랜덤값을 채울 차원을 지정

array([[0.41142662, 0.17726085, 0.77079027],
       [0.0378205 , 0.33131582, 0.44711728]])

### np.random.randn
* 정규분포 random 값 만들기

In [25]:
np.random.randn(10)

array([-0.10084633,  0.97207815, -0.55305547,  2.03926158, -0.44937537,
        1.27169962,  0.23430993,  0.91676766, -1.70426924, -1.06601719])

### np.random.uniform
* 균등분포 random값 만들기

In [26]:
np.random.uniform(1.0, 3.0, size=(4, 5)) # 1.0 ~ 3.0까지 균등분포 랜덤값 생성

array([[1.26112187, 2.5566794 , 1.64439756, 1.74933003, 2.64163821],
       [2.48558798, 1.96277634, 1.19719303, 2.05128892, 1.32489963],
       [2.92391022, 2.86408493, 1.31740391, 1.08989593, 1.32540124],
       [2.78729043, 2.74281524, 2.2784138 , 1.13338771, 1.80728063]])

### 정수 random 만들기
* np.random.randint

In [27]:
np.random.randint(1, 100, size=(5, ))

array([93, 15, 68, 11, 95])

In [30]:
np.random.randint(1, 100, size=(5, 1)) # 2차원 배열에 랜덤 정수 채우기

array([[ 1],
       [43],
       [10],
       [26],
       [53]])

In [29]:
np.random.randint(1, 100, size=(3, 4, 5))

array([[[15,  6, 55, 43, 68],
        [58, 24, 42, 47, 10],
        [96, 64, 65, 82, 70],
        [54, 23, 46,  9, 68]],

       [[93, 85, 97,  6, 32],
        [23, 48, 72,  6, 57],
        [44, 22, 86, 81, 29],
        [45, 71, 90, 55, 93]],

       [[95, 42, 67, 45, 43],
        [27, 91, 67, 60, 50],
        [54, 37, 53, 80, 60],
        [92,  1, 29, 73, 49]]])

### 정수 random sampling 하기
* np.random.choice
* random sampling : 일정한 범위 내에서 필요한 정수를 랜덤으로 추출
* 미니 배치를 만들 때 사용합니다

In [31]:
np.random.choice(100, size=(3, 4))

array([[10, 39, 66, 64],
       [82, 29, 38, 88],
       [10,  0, 19,  3]])

In [32]:
# 임의의 배열을 만들고 그 안에서 랜덤하게 추출할 수 있도록 함
arr = np.arange(1, 6)

# replace 가 True면 원소를 중복, False면 중복 추출 x
np.random.choice(arr, size=(2, 2), replace=False)

array([[3, 2],
       [5, 1]])

## 인덱스와 슬라이싱

In [33]:
arr = np.arange(1, 11).reshape(2, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
arr[0][2]

3

In [35]:
arr[0, 2]

3

In [36]:
arr[:, 2] # 2차원 배열 내에서 1차원 배열은 전채 선택, 0차원 스탈라 값은 2번째 인덱스에 있는 것을 선택

array([3, 8])

* Quiz!!

In [38]:
arr = np.arange(1, 37).reshape(3, 4, 3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [43]:
arr[:,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[13, 14],
        [16, 17]],

       [[25, 26],
        [28, 29]]])

In [46]:
arr[1:, 1:3, 1:3]

array([[[17, 18],
        [20, 21]],

       [[29, 30],
        [32, 33]]])

## 배열의 차원과 형상
* 형상( shape )
* 차원( ndim )

In [47]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
arr.shape

(3, 4)

In [49]:
arr.ndim

2

### 차원수 확장하기
* 항상 같은 예시는 아니지만, 보통은 이미지 분석( CNN )을 하기 위해 데이터 전처리를 하면서 사용 된다.
* tensorflow는 tf.newaxis 활용, np.newaxis를 활용

In [50]:
arr.shape

(3, 4)

In [52]:
tmp_arr = arr[np.newaxis, :, :, np.newaxis] # arr의 첫 번째와 마지막에 차원을 1씩 확장
tmp_arr

array([[[[ 0],
         [ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6],
         [ 7]],

        [[ 8],
         [ 9],
         [10],
         [11]]]])

In [54]:
# 실제 데이터를 다룰 때는 shape 만 확인
tmp_arr.shape

(1, 3, 4, 1)

In [57]:
# 각 차원이 1인 차원 삭제하기
tmp_arr2 = np.squeeze(tmp_arr)
tmp_arr2.shape

(3, 4)

* spread 연산자 활용하기
    * 슬라이싱 도중에 특정 차원 부터는 전체를 선택할 때 사용한다

In [59]:
tmp_arr3 = arr[np.newaxis, ..., np.newaxis] # ... => spread 연산자
tmp_arr3.shape

(1, 3, 4, 1)

### 배열의 형상 ( shape ) 바꾸기
* np.newaxis 를 활용해서 축을 추가( 차원수를 늘린다 )
* 평탄화
    * ravel : 원본 배열을 평탄화 시킨 **참조**배열을 만들어 낸다
            ( View 또는 Reference를 만들었다 라고 표현한다 )
    * flattan : 평탄화 시킨 **복사된** 배열을 만들어 낸다
* 형상 변환
    * reshape

In [60]:
x = np.arange(15).reshape(3, 5)
x.shape

(3, 5)

In [61]:
print("원본 x : \n{}".format(x))

원본 x : 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [62]:
temp = np.ravel(x)
print("ravel로 평탄화된 x의 shape : {}".format(x.shape))
print("ravel로 평탄화된 x : {}".format(temp))

ravel로 평탄화된 x의 shape : (3, 5)
ravel로 평탄화된 x : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [66]:
temp[0] = 100
print(x)

[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


* ravel 함수는 원본의 참조본을 만들어 낸다

In [65]:
# flatten 은 본사본을 만든다
y = np.arange(15).reshape(3, 5)
temp2 = y.flatten()

print("flatten로 평탄화된 y의 shape : {}".format(y.shape))
print("flatten로 평탄화된 y : {}".format(temp2))

flatten로 평탄화된 y의 shape : (3, 5)
flatten로 평탄화된 y : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [67]:
temp2[0] = 100
print(temp2)
print(y)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


* reshape 사용하기

In [68]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

* reshape 팁 : reshape 함수 내의 모든 숫자을 곱했을 때 스칼라 원소의 개수와 같아야 한다

In [69]:
x.reshape(2, 5, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

* -1 을 reshape 에 넣으면 남는 숫자를 자동으로 계산해 준다

In [70]:
x.reshape(2, 2, -1) # 2 * 2 = 4 따라서 -1 = 5

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [71]:
x.reshape(2, -1, 2) 

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## 브로드 캐스팅
* 차원수가 다른 배열끼리의 연산
* 차원이 달라도 0차원 스칼라의 개수가 똑같으면 연산이 가능

In [72]:
x = np.arange(20).reshape(4, 5)
y = np.arange(20, 40).reshape(4, 5)

print(x)
print()
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


* 차원과 원소의 수가 같으면 자연스럽게 원소끼리 **연산을 할 수 있다**

In [73]:
x * y

array([[  0,  21,  44,  69,  96],
       [125, 156, 189, 224, 261],
       [300, 341, 384, 429, 476],
       [525, 576, 629, 684, 741]])

In [74]:
x / y

array([[0.        , 0.04761905, 0.09090909, 0.13043478, 0.16666667],
       [0.2       , 0.23076923, 0.25925926, 0.28571429, 0.31034483],
       [0.33333333, 0.35483871, 0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946, 0.47368421, 0.48717949]])

In [75]:
x * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

* x는 2차원, 2는 0차원 스칼라 값이다.
* 2의 차원이 곱해지는 배열인 x의 shape으로 확장한다

In [77]:
# shape이 다를 때의 연산
# b : 1차원, d = 2차원
a = np.arange(12).reshape(4, 3) # (4, 3)
b = np.arange(100, 103) # (3, )
c = np.arange(1000, 1004) # (4, )
d = b.reshape(1, 3)

In [78]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [79]:
# a + c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

## 전치 행렬 만들기
* 행렬 A의 행과 열의 인덱스를 바꾼 것을 전치 행렬이라고 한다
* 보통 Transpose 했다고 이야기 한다.

In [80]:
e = np.arange(6).reshape(2, 3)
e

array([[0, 1, 2],
       [3, 4, 5]])

In [81]:
# ndarray 에서 T만 호출해 주면 된다.
e.T

array([[0, 3],
       [1, 4],
       [2, 5]])

* 역전파에서 사용