# Numpy

In [1]:
import numpy as np

## Numpy 활용 배열 만들기

In [2]:
array1 = np.array([1, 2, 3])
array1.shape

(3,)

In [6]:
array2 = np.array([[1, 2, 3],
                  [2, 3, 4]])
array2.shape

(2, 3)

In [7]:
array3 = np.array([[1, 2, 3]])
array3.shape

(1, 3)

In [8]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,
                                                             array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


## Data Type 
###  Ask data type : dtype

In [9]:
list1 = [1, 2, 3]
array1 = np.array(list1)
print(array1, array1.dtype)

[1 2 3] int32


In [12]:
list2 = [1, 2, 'Hello']
array2 = np.array(list2)
print(array2, array2.dtype)

['1' '2' 'Hello'] <U11


In [14]:
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)
# ndarray 는 모두 같은 data tyoe 이여아 한다.

[1. 2. 3.] float64


### Change data type : astype

In [18]:
array1_fl = array1.astype(float)
print(array1_fl, array1_fl.dtype)

[1. 2. 3.] float64


## For easy making
* arrange, zeros, ones

In [21]:
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [22]:
zero = np.zeros((3, 2), dtype='int32')
print(zero)

[[0 0]
 [0 0]
 [0 0]]


In [23]:
ones = np.ones((2, 3), dtype='int32')
print(ones)

[[1 1 1]
 [1 1 1]]


## Change dimension and size
* reshape
* 사이즈에 주의해야 한다

In [24]:
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
array2 = array1.reshape(2, 5)
print(array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [28]:
array3 = array1.reshape(5, 2)
print(array3)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


* -1 을 사용할 경우

In [ ]:
array2 = array1.reshape(-1, 5)
print(array2)

In [31]:
array3 = array1.reshape(5, -1)
print(array3)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


* reshape(-1, 1) 로 주로 사용됨
* 원본에 상관없이 1개의 컬럼을 가진 2차원으로 리턴

## Indexing
* 특정 데이터 : 단일 값
* Slicing : 다중 값
* Fancy Indexing
* Boolean Indexing

In [35]:
# Fancy Indexing 

array1 = np.arange(1, 10)
array2 = array1.reshape(3, 3)

array2[[0, 1], 2]    # [0, 1] = index, 2 = column
array2[[0, 1], 0:2]  # 0:2 = 0,1 column

array([[1, 2],
       [4, 5]])

In [36]:
# boolean Indexing
# 조건 필터링과 검색을 동시에

array3 = array1[array1>5]    # [] = 조건
print(array3)

[6 7 8 9]


## Sorting
* sort()

In [38]:
# sort 두가지 방법
# np.sort()  :  Numpy 에서 직접 호출
# ndarray.sort()  :  행렬 차제에서 호출 => Return None

In [39]:
org = np.array([3, 1, 9, 5])
sort_arr = np.sort(org)
sort_arr

array([1, 3, 5, 9])

In [41]:
org.sort()    # return None => 원본을 수정한다
org

array([1, 3, 5, 9])

In [42]:
reverse_arr = np.sort(org)[::-1]
reverse_arr

array([9, 5, 3, 1])

In [43]:
# axis = 0  :  'row 로 정렬'
# axis = 1  :  'column 으로 정렬'

* argsort() : 정렬 후 원본 행렬의 인덱스

In [45]:
org = np.array([3, 1, 9, 5])
ind = np.argsort(org)
ind

array([1, 0, 3, 2], dtype=int64)

In [46]:
org = np.array([3, 1, 9, 5])
ind_rev = np.argsort(org)[::-1]
ind_rev

array([2, 3, 0, 1], dtype=int64)

## 선형대수 연산
### 행렬 내적
* np.dot()

### 전치 행렬
* transpose