# Tensor란?

Tensor : 배열

* Rank 시스템이 있는 배열
* 0 Rank Tensor - Scalar - 상수
* 1 Rank Tensor - Array(Vector) - 1차원 배열
* 2 Rank Tensor - Matrix - 행렬
* 3 Rank Tensor - Tensor - 3차원 배열
* 4 Rank Tensor - Tensor - 4차원 배열...

# TensorFlow는?
* Tensor가 지나다닐 수 있는 **계산그래프**를 만들어 놓고 Tensor를 흘려(Flow) 보낸다.

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# 각종 시퀀스를 Tensor로 변환이 가능

# 1. list => tensor
tf.constant([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [3]:
# 2. tuple => tensor
tf.constant((1, 2, 3))

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [4]:
# 3. ndarray => tensor
arr = np.array([1, 2, 3])
tf.constant(arr)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

# Tensor 정보 확인하기

In [5]:
tensor = tf.constant(np.array([1, 2, 3]))
tensor.shape

TensorShape([3])

In [6]:
tensor = tf.constant(np.arange(0, 10).reshape(2, 5))
tensor.shape

TensorShape([2, 5])

In [7]:
tensor.dtype

tf.int64

In [8]:
tensor = tf.constant(np.random.randn(2, 3))
tensor.dtype

tf.float64

In [ ]:
# 텐서를 구성하는 원소 중 데이터의 타입이 가장 큰 것이 텐서의 데이터 타입이 된다.
# 예를 들어 텐서에 정수와 실수가 섞여있으면 텐서의 타입은 실수가 된다.

tensor = tf.constant([1, 2.1, 3])
tensor.dtype

In [9]:
# 강제로 데이터 타입을 지정
tensor = tf.constant([1, 2, 3], dtype=tf.float32)
tensor.dtype

tf.float32

In [12]:
# tf.cast 를 활용해서 텐서의 데이터 타입을 변경
tf.cast(tensor, tf.uint8).dtype

tf.uint8

In [13]:
# numpy와 tensorflow는 상호간에 호환이 가능

# 1. tensor를 ndarray로 바꿔보기
tensor.numpy()

array([1., 2., 3.], dtype=float32)

In [14]:
# np.array를 이용해서 tensor를 ndarray로 바꾸기
np.array(tensor)

array([1., 2., 3.], dtype=float32)

# Tensorflow의 난수 생성

In [15]:
# numpy로 정규분포 만들기
np.random.randn(9)

array([ 6.55633010e-01,  1.61397066e+00, -8.51681644e-01, -3.24937501e-01,
        1.76707898e-01,  4.20356922e-04, -2.05369480e-01,  5.35344413e-01,
       -2.61366145e-01])

In [16]:
# tensorflow로 정규분포 만들기
tf.random.normal((3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.6898024 , -1.5270109 ,  0.09168899],
       [ 0.28537658,  0.6628939 , -1.2905841 ],
       [ 0.92743444, -2.0191107 , -0.35576352]], dtype=float32)>

In [17]:
# tensorflow로 균등분포 만들기
tf.random.uniform((3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.08536494, 0.34026957, 0.15079808],
       [0.4850433 , 0.52614176, 0.6907536 ],
       [0.9673277 , 0.5821061 , 0.3036914 ]], dtype=float32)>

# Tensorflow로 One Hot Encoding

In [18]:
from tensorflow.keras.utils import to_categorical

In [19]:
to_categorical(1, 5)

array([0., 1., 0., 0., 0.], dtype=float32)